// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MemoryWayback")>]
[<assembly: AssemblyProductAttribute("MemoryWayback")>]
[<assembly: AssemblyDescriptionAttribute("browse through old memories (photos, videos)")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MemoryWayback"
    let [<Literal>] AssemblyProduct = "MemoryWayback"
    let [<Literal>] AssemblyDescription = "browse through old memories (photos, videos)"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
